spring.application.name=rate_limit

# Load .env file (no extra library needed)
spring.config.import=optional:file:.env[.properties]

# Redis Configuration
spring.data.redis.url=${REDIS_URL}

# Server Port (Render sets PORT env var)
server.port=${PORT}